### PR TITLE
Add Directory Information and Docker build

### PR DESCRIPTION
**Pull request by sscholl**
add Search implementation for basic search for Directory Information Tree and the LDAP Root DSE (was required by zammad help desk)

### CODE REVIEW

**Comment by milux** [comment]
Looks nice. Why were most of the files moved to the /app subfolder?
Can you please explain the specific reason for this?

**Comment by sscholl** [comment]
Because i copy the content of app to the Dockerfile. I can change this if you want. Then also the content of the root folder is inside the Dockerfile, which is not a problem. Then I would create another PR.

**Comment by milux** [comment]
By "Dockerfile", do you mean the docker image you're creating?
I consider this strategy with the separate folder a bit unclean... afaik it's best practice to use a `.dockerignore` file, see here: https://stackoverflow.com/questions/43747776/copy-with-docker-but-with-exclusion

2 further questions:
- Could we use docker:alpine as base image? Apart from being smaller, it's afaik also more secure (although this doesn't really matter indeed ^^)
~~Do you have any idea how the output of node (stdout/stderr) could be piped to the logging service of the host OS? I would prefer to stick to `journalctl`...~~
Edit: Forget about this, just observed that docker has some nice facilities for that out-of-the-box. :wink:

**Comment by sscholl** [comment]
Hey milux,
i reworked it now. I think, all your point are done. You can set up https://cloud.docker.com to build the image. Maybe change the image names as well in the docker-compose file. I attached the configuration.
image
Best Regards,
Simon

**Pull request merged**
